; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "RHI"
#define MyAppVersion "2.5.4"
#define MyAppPublisher "RankFTW"
#define MyAppURL "www.github.com/rankftw"
#define MyAppExeName "RHI.exe"
#define PublishDir "publish\RHI-2.5.4-zhCN-win-x64"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{05342962-55F5-4BA3-BFD3-DBA01D2B8BCB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=installers
OutputBaseFilename=RHI-Setup
SetupIconFile=RenoDXCommander\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic
ShowLanguageDialog=yes
LanguageDetectionMethod=uiLanguage

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "Installer\Languages\ChineseSimplified.isl"

[CustomMessages]
english.SelectLanguageTitle=Select RHI Language
english.SelectLanguageLabel=Select the language for Setup and RHI:
chinesesimplified.SelectLanguageTitle=选择 RHI 语言
chinesesimplified.SelectLanguageLabel=选择安装向导和 RHI 使用的语言：

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PublishDir}\*"; DestDir: "{app}"; Excludes: "*.pdb"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\RHI"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function IsRhiRunning(): Boolean;
var
  WMI: Variant;
  Procs: Variant;
begin
  Result := False;
  try
    WMI := CreateOleObject('WbemScripting.SWbemLocator');
    WMI := WMI.ConnectServer('.', 'root\cimv2');
    Procs := WMI.ExecQuery('SELECT * FROM Win32_Process WHERE Name="RHI.exe"');
    Result := (Procs.Count > 0);
  except
  end;
end;

procedure SetRhiLanguage(const LanguageCode: String);
var
  SettingsDir, SettingsFile, Content: String;
  InputLines, OutputLines: TArrayOfString;
  KeyPos, ColonPos, QuoteStart, QuoteEnd, RelativePos, I: Integer;
begin
  SettingsDir := ExpandConstant('{localappdata}\RHI');
  SettingsFile := SettingsDir + '\settings.json';
  if not DirExists(SettingsDir) then
    ForceDirectories(SettingsDir);

  Content := '';
  if LoadStringsFromFile(SettingsFile, InputLines) then
  begin
    for I := 0 to GetArrayLength(InputLines) - 1 do
    begin
      if I > 0 then
        Content := Content + #13#10;
      Content := Content + InputLines[I];
    end;
  end
  else
    Content := '{}';

  // settings.json is produced by System.Text.Json and UiLanguage values contain no escapes.
  KeyPos := Pos('"UiLanguage"', Content);
  if KeyPos > 0 then
  begin
    RelativePos := Pos(':', Copy(Content, KeyPos, MaxInt));
    ColonPos := KeyPos + RelativePos - 1;
    RelativePos := Pos('"', Copy(Content, ColonPos + 1, MaxInt));
    QuoteStart := ColonPos + RelativePos;
    RelativePos := Pos('"', Copy(Content, QuoteStart + 1, MaxInt));
    QuoteEnd := QuoteStart + RelativePos;
    Delete(Content, QuoteStart, QuoteEnd - QuoteStart + 1);
    Insert(LanguageCode, Content, QuoteStart);
  end
  else if Content = '' then
    Content := '{"UiLanguage":"' + LanguageCode + '"}'
  else if Trim(Content) = '{}' then
    Content := '{"UiLanguage":"' + LanguageCode + '"}'
  else
    Insert('"UiLanguage":"' + LanguageCode + '",', Content, Pos('{', Content) + 1);

  SetArrayLength(OutputLines, 1);
  OutputLines[0] := Content;
  SaveStringsToUTF8File(SettingsFile, OutputLines, False);
end;

function InitializeSetup(): Boolean;
var
  SignalDir, SignalPath: String;
  WaitCount: Integer;
begin
  Result := True;

  // Only signal if RHI is actually running
  if not IsRhiRunning() then Exit;

  // Write shutdown signal file to %LocalAppData%\RHI\
  SignalDir := ExpandConstant('{localappdata}\RHI');
  if not DirExists(SignalDir) then
    ForceDirectories(SignalDir);
  SignalPath := SignalDir + '\rhi_shutdown_requested';
  SaveStringToFile(SignalPath, 'update', False);

  // Wait up to 10 seconds for RHI to close itself
  WaitCount := 0;
  while (WaitCount < 20) and IsRhiRunning() do
  begin
    Sleep(500);
    WaitCount := WaitCount + 1;
  end;

  // If still running, Inno's default CloseApplications will handle it
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  LanguageFileLines: TArrayOfString;
  LanguageCode: String;
begin
  if CurStep = ssPostInstall then
  begin
    if ActiveLanguage = 'chinesesimplified' then
      LanguageCode := 'zh-CN'
    else
      LanguageCode := 'en-US';

    SetRhiLanguage(LanguageCode);

    // Store a machine-level default so the choice also works when Setup is
    // elevated under a different account than the person who launched it.
    SetArrayLength(LanguageFileLines, 1);
    LanguageFileLines[0] := LanguageCode;
    SaveStringsToUTF8File(ExpandConstant('{app}\ui-language.txt'), LanguageFileLines, False);
  end;
end;

