#!/usr/bin/env python3
"""
RHI Game Report Decoder

Decodes the base64 game report code generated by the "Copy Report" button
in RHI's override panel.

Usage:
    python decode_game_report.py <base64_code>
    python decode_game_report.py          # prompts for input
    echo "<base64_code>" | python decode_game_report.py
"""

import sys
import base64
import json
import os
import re
from datetime import datetime


def decode(code):
    return json.loads(base64.b64decode(code.strip()).decode("utf-8"))


def pf(label, value, indent=2):
    pad = " " * indent
    if isinstance(value, bool):
        value = "Yes" if value else "No"
    if value is None or value == "":
        value = "-"
    print(f"{pad}{label:28s} {value}")


def print_diff(label, detected_val, corrected_val, indent=4):
    pad = " " * indent
    if isinstance(detected_val, bool):
        detected_val = "Yes" if detected_val else "No"
    if isinstance(corrected_val, bool):
        corrected_val = "Yes" if corrected_val else "No"
    dv = detected_val if detected_val not in (None, "") else "-"
    cv = corrected_val if corrected_val not in (None, "") else "-"
    if str(dv) == str(cv):
        print(f"{pad}{label:28s} {dv}  (same)")
    else:
        print(f"{pad}{label:28s} {dv}  ->  {cv}  ***")


def slugify(name):
    """Turn a game name into a safe filename slug."""
    s = name.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_-]+", "-", s).strip("-")
    return s or "unknown"


def write_md_report(d, script_dir):
    """Write a markdown report file next to the script."""
    game = d.get("gameName", "Unknown")
    now = datetime.now()
    stamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{slugify(game)}_{stamp}.md"
    filepath = os.path.join(script_dir, filename)

    lines = []
    lines.append(f"# RHI Game Report — {game}")
    lines.append(f"**Generated:** {now.strftime('%Y-%m-%d %H:%M:%S')}\n")

    # Game Identity
    lines.append("## Game Identity")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Game Name | {game} |")
    lines.append(f"| Original Store Name | {d.get('originalStoreName', '-')} |")
    lines.append(f"| Store / Platform | {d.get('store', '-')} |")
    lines.append("")

    # Detected vs Corrected
    det = d.get("detected", {})
    cor = d.get("corrected", {})
    if det or cor:
        lines.append("## Detected vs Corrected")
        lines.append("| Field | Detected | Corrected |")
        lines.append("|-------|----------|-----------|")
        diff_fields = [
            ("Install Path", "installPath"),
            ("Engine", "engine"),
            ("Bitness", "is32Bit"),
            ("Graphics API", "graphicsApi"),
            ("Detected APIs", "detectedApis"),
            ("Wiki Match", "wikiMatch"),
        ]
        for label, key in diff_fields:
            dv = det.get(key, "-")
            cv = cor.get(key, dv)
            if key == "is32Bit":
                dv = "32-bit" if dv else "64-bit"
                cv = "32-bit" if cv else "64-bit"
            marker = " ⚠️" if str(dv) != str(cv) else ""
            lines.append(f"| {label} | {dv} | {cv}{marker} |")
        lines.append("")

        # User corrections
        lines.append("## User Corrections Applied")
        override_fields = [
            ("Bitness Override", "bitnessOverride"),
            ("API Override", "apiOverride"),
            ("Folder Override", "folderOverride"),
            ("DLL Override (ReShade)", "dllOverride"),
            ("DLL Override (DC)", "dcDllOverride"),
            ("Wiki Name Override", "wikiNameOverride"),
        ]
        any_override = False
        for label, key in override_fields:
            val = cor.get(key)
            if val and val not in ("Auto", "", "-"):
                if not any_override:
                    lines.append("| Override | Value |")
                    lines.append("|----------|-------|")
                lines.append(f"| {label} | {val} |")
                any_override = True
        if not any_override:
            lines.append("*(none)*")
        lines.append("")

    # Flags
    def yn(v):
        if isinstance(v, bool):
            return "Yes" if v else "No"
        return v if v not in (None, "") else "-"

    lines.append("## Flags")
    lines.append("| Flag | Value |")
    lines.append("|------|-------|")
    for label, key in [
        ("Luma Mode", "isLumaMode"), ("Luma Mod", "lumaMod"),
        ("UE-Extended", "ueExtended"), ("Native HDR", "nativeHdr"),
        ("RE Engine", "isREEngine"), ("Blacklisted", "isBlacklisted"),
        ("Hidden", "isHidden"), ("Favourite", "isFavourite"),
    ]:
        lines.append(f"| {label} | {yn(d.get(key))} |")
    lines.append("")

    # Components
    comps = d.get("components", [])
    if comps:
        lines.append("## Components")
        lines.append("| Component | Status | Version | Filename |")
        lines.append("|-----------|--------|---------|----------|")
        for c in comps:
            n = c.get("name", "?")
            s = c.get("status", "?")
            v = c.get("version", "-")
            f = c.get("filename", "-")
            lines.append(f"| {n} | {s} | {v} | {f} |")
        lines.append("")

    # Overrides
    ov = d.get("overrides", {})
    if ov:
        lines.append("## All Overrides")
        lines.append("| Key | Value |")
        lines.append("|-----|-------|")
        for k, v in ov.items():
            lines.append(f"| {k} | {v if v not in (None, '') else '-'} |")
        lines.append("")

    # Addons
    ad = d.get("addons", {})
    if ad:
        lines.append("## Addons")
        lines.append(f"- **Mode:** {ad.get('mode', '-')}")
        if ad.get("enabled"):
            lines.append(f"- **Enabled:** {', '.join(ad['enabled'])}")
        if ad.get("perGameSelection"):
            lines.append(f"- **Per-game:** {', '.join(ad['perGameSelection'])}")
        lines.append("")

    # Meta
    lines.append("## Meta")
    lines.append(f"- **RHI Version:** {d.get('rhiVersion', '-')}")
    lines.append(f"- **Report Timestamp:** {d.get('timestamp', '-')}")
    lines.append("")

    # User note
    note = d.get("userNote", "")
    if note:
        lines.append("## User Note")
        lines.append(note)
        lines.append("")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath


def print_report(d):
    print("=" * 64)
    print(f"  RHI Game Report - {d.get('gameName', '?')}")
    print("=" * 64)

    # Game identity
    print("\n  --- Game Identity ---")
    pf("Game Name", d.get("gameName"))
    pf("Original Store Name", d.get("originalStoreName"))
    pf("Store / Platform", d.get("store"))

    # Detected vs Corrected diff
    det = d.get("detected", {})
    cor = d.get("corrected", {})
    if det or cor:
        print("\n  --- Detected vs Corrected ---")
        diff_fields = [
            ("Install Path", "installPath"),
            ("Engine", "engine"),
            ("Bitness", "is32Bit"),
            ("Graphics API", "graphicsApi"),
            ("Detected APIs", "detectedApis"),
            ("Wiki Match", "wikiMatch"),
        ]
        has_changes = False
        for label, key in diff_fields:
            dv = det.get(key, "-")
            cv = cor.get(key, dv)
            if key == "is32Bit":
                dv = "32-bit" if dv else "64-bit"
                cv = "32-bit" if cv else "64-bit"
            print_diff(label, dv, cv)
            if str(dv) != str(cv):
                has_changes = True

        # Show override-specific corrections
        override_fields = [
            ("Bitness Override", "bitnessOverride"),
            ("API Override", "apiOverride"),
            ("Folder Override", "folderOverride"),
            ("DLL Override (ReShade)", "dllOverride"),
            ("DLL Override (DC)", "dcDllOverride"),
            ("Wiki Name Override", "wikiNameOverride"),
        ]
        print("\n  --- User Corrections Applied ---")
        any_override = False
        for label, key in override_fields:
            val = cor.get(key)
            if val and val not in ("Auto", "", "-"):
                pf(label, val, indent=4)
                any_override = True
        if not any_override:
            print("    (none)")

        if has_changes:
            print("\n  *** Fields marked with *** differ from auto-detected values")
            print("      and may need manifest updates.")

    # Flags
    print("\n  --- Flags ---")
    pf("Luma Mode", d.get("isLumaMode"))
    pf("Luma Mod", d.get("lumaMod"))
    pf("UE-Extended", d.get("ueExtended"))
    pf("Native HDR", d.get("nativeHdr"))
    pf("RE Engine", d.get("isREEngine"))
    pf("Blacklisted", d.get("isBlacklisted"))
    pf("Hidden", d.get("isHidden"))
    pf("Favourite", d.get("isFavourite"))

    # Components
    print("\n  --- Components ---")
    for c in d.get("components", []):
        n = c.get("name", "?")
        s = c.get("status", "?")
        v = f" v{c['version']}" if c.get("version") else ""
        f = f" [{c['filename']}]" if c.get("filename") else ""
        print(f"    {n:22s} {s}{v}{f}")

    # Overrides (full dump)
    ov = d.get("overrides", {})
    if ov:
        print("\n  --- All Overrides ---")
        for k, v in ov.items():
            pf(k, v, indent=4)

    # Addons
    ad = d.get("addons", {})
    if ad:
        print("\n  --- Addons ---")
        pf("Mode", ad.get("mode"), indent=4)
        if ad.get("enabled"):
            pf("Enabled", ", ".join(ad["enabled"]), indent=4)
        if ad.get("perGameSelection"):
            pf("Per-game", ", ".join(ad["perGameSelection"]), indent=4)

    # Meta
    print("\n  --- Meta ---")
    pf("RHI Version", d.get("rhiVersion"))
    pf("Generated", d.get("timestamp"))

    # User note
    note = d.get("userNote", "")
    if note:
        print("\n  --- User Note ---")
        for line in note.split("\n"):
            print(f"    {line}")

    print("\n" + "=" * 64)


def main():
    if not sys.stdin.isatty():
        code = sys.stdin.read().strip()
    elif len(sys.argv) > 1:
        code = sys.argv[1].strip()
    else:
        code = input("Paste the RHI game report code: ").strip()

    if not code:
        print("No code provided.")
        sys.exit(1)

    try:
        data = decode(code)
    except Exception as e:
        print(f"Failed to decode: {e}")
        sys.exit(1)

    print_report(data)

    # Write markdown report next to this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    md_path = write_md_report(data, script_dir)
    print(f"\n  Report saved to: {md_path}")

    print("\n  --- Raw JSON ---")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
